apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.name }}-secret
  namespace: {{ .Values.db.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_PASSWORD: {{ .Values.db.secrets.MYSQL_PASSWORD }}