apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.db.namespace }}
  labels:
{{- toYaml .Values.db.labels | nindent 4 }}
spec:
  ports:
  - port: 3306            # the port on which the service is listening
    protocol: TCP
    targetPort: {{ .Values.db.containerPorts.mysql }}      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    id: {{.Values.db.labels.id }}       # Pod label that service is using to select Pods