apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wp.name }}
  namespace: {{ .Values.wp.namespace }}
  labels:
{{- toYaml .Values.wp.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      id: {{.Values.wp.labels.id }}
  replicas: {{ .Values.wp.replicas }}
  template:
    metadata:
      labels:
{{- toYaml .Values.wp.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.wp.name }}
        image: {{ .Values.wp.image.repository }}:{{ .Values.wp.image.tag }}
        imagePullPolicy: {{ .Values.wp.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Values.wp.name }}-configmap
              optional: false
          - secretRef:
              name: {{ .Values.wp.name }}-secret
              optional: false
        ports:
        - containerPort: {{ .Values.wp.containerPorts.http }}