apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.wp.name }}-secret
  namespace: {{ .Values.wp.namespace }}
type: Opaque
data:
    WORDPRESS_DB_PASSWORD: {{ .Values.wp.secrets.WORDPRESS_DB_PASSWORD }}