apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wp.servicename }}
  namespace: {{ .Values.wp.namespace }}
  labels:
{{- toYaml .Values.wp.labels | nindent 4 }}
spec:
  ports:
  - port: 80            # the port on which the service is listening
    protocol: TCP
    targetPort: {{ .Values.wp.containerPorts.http }}      # the port exposed by Pod (we defined in the deployment as part of `containerPort)
  selector:
    id: {{.Values.wp.labels.id }}